apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecocycle
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mariadb.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
images:
  - name: ghcr.io/ayoub-gaouet/ecocycle-tn
    newTag: 32a46ef
