apiVersion: v1
kind: Secret
metadata:
  name: ecocycle-user-service-secret
type: Opaque
stringData:
  DB_PASSWORD: ecocycle
  JWT_SECRET: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
---
apiVersion: v1
kind: Secret
metadata:
  name: ecocycle-mariadb-secret
type: Opaque
stringData:
  MARIADB_DATABASE: ecocycle_tn
  MARIADB_USER: ecocycle
  MARIADB_PASSWORD: ecocycle
  MARIADB_ROOT_PASSWORD: root
